export const ADD_ACTION = 'ADD_ACTION';
export const REMOVE_ACTION = 'REMOVE_ACTION';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const COMPLETE_ACTION = 'COMPLETE_ACTION';
export const PRIORITY_ACTION = 'PRIORITY_ACTION';